// Generated by CoffeeScript 1.6.3
(function() {
  var mongoose = require('mongoose');
  var autoIncrement = require('mongoose-auto-increment');

  _ = require('underscore');

  config = require('../config');
  
  DB = config.getDB();

  Schema = mongoose.Schema;

  conn = mongoose.connect(DB);

  autoIncrement.initialize(conn);
  
  mongoose.connection.on("error", function(err) {
    console.error("MongoDB error: %s", err);
  });

  mongoose.set("debug", false);

  module.exports.conn = conn;

  module.exports.createSchemaModel = function(modelName, schemaJson, options) {
    schema = new Schema(schemaJson);
    if (options != null ? options.methods : void 0) {
      _(schema.methods).extend(options.methods);
    }
    if (modelName=='Patient')
      schema.plugin(autoIncrement.plugin, { model: modelName, field: 'patientId' });

    schema.set('autoIndex', false);
    return conn.model(modelName, schema);
  };
}).call(this);